#!/bin/bash
set -e

sudo apt-get update
sudo apt-get install -y nginx
sudo apt-get install -y ufw
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sudo systemctl enable nginx
sudo systemctl restart nginx
sudo service nginx start
systemctl status nginx
